_target_: src.models.Finetuning

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0001
  weight_decay: 0.00001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

backbone:
  _target_: src.models.backbones.AlexNet
  input_channels: 3
  size: 32


heads:
  _target_: src.models.heads.HeadsTIL
  input_dim: 2048