_target_: models.Piggyback

threshold: 5e-03

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

backbone:
  _target_: models.backbones.WeightMaskedMLP
  input_dim: 784
  hidden_dims: [256, 100]
  output_dim: 64

heads:
  _target_: models.heads.HeadsTIL
  input_dim: ${model.backbone.output_dim}