# train with many loggers at once

defaults:
  - csv.yaml
  - tensorboard.yaml
  # - comet.yaml
  # - mlflow.yaml
  # - neptune.yaml
  # - wandb.yaml

pylogger:
  log_dir: ${paths.log_dir}
  filename: ${paths.pylog_filename}
  level: 10 # logging.DEBUG
  fmt: "%(asctime)s %(name)s %(levelname)s: %(message)s"



