_target_: src.models.HATCompareLoss

s_max: 400.0
reg:
  _target_: src.models.regs.MaskSparseMultiReg
  factor: 0.1


optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

backbone:
  _target_: src.models.backbones.MaskedMLP
  input_dim: 784
  hidden_dims: [256, 100]
  output_dim: 64

head:
  _target_: src.models.heads.HeadTIL
  input_dim: ${model.backbone.output_dim}
