from .finetuning import Finetuning
from .random import Random
from .joint import Joint
from .lwf import LwF
from .ewc import EWC
from .packnet import PackNet
from .piggyback import Piggyback
from .hat import HAT
from .adahat import AdaHAT
from .hat_non_union import HATNonUnion
from .hat_compare_loss import HATCompareLoss
